# TODO move tasks below to roles folders
---
- hosts: appservers
  sudo: yes
  sudo_user: deploy
  tasks:
    - name: Install Ruby build dependency
      sudo: yes
      sudo_user: root
      apt:
        name={{ item }}
        state=installed
      with_items:
        - git-core 
        - curl
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - python-software-properties
        - libffi-dev
        - imagemagick
    - name: Install rbenv
      git: 
        repo=https://github.com/sstephenson/rbenv.git
        dest=~/.rbenv

    - name: add rbenv bash path 
      lineinfile:
        dest=~/.bashrc
        line='{{ item.line }}'
        create=yes
      with_items:
        - {line: 'export PATH="$HOME/.rbenv/bin:$PATH"'}
        - {line: 'eval "$(rbenv init -)"'}

    - name: Install Ruby-build
      git:
        repo=https://github.com/sstephenson/ruby-build.git 
        dest=~/.rbenv/plugins/ruby-build

    - name: Install Ruby 2.2.2
      command: bash -ic 'rbenv install 2.2.2 -s'
      command: bash -ic 'rbenv install 2.2.2 -s'

    - name: Active Ruby version
      command: bash -ic 'rbenv global 2.2.2; rbenv local 2.2.2; rbenv rehash'

    - name: add .gemrc
      lineinfile:
        dest=~/.gemrc
        line='{{ item.line }}'
        create=yes
      with_items:
        - {line: 'gem: --no-ri --no-rdoc'}

    - name: Install gem Bundler
      command: bash -ic 'gem install bundler'

    - name: add NodeJS repo
      sudo: yes
      sudo_user: root
      apt_repository: repo='ppa:chris-lea/node.js' state=present

    - name: Install NodeJS
      sudo: yes
      sudo_user: root
      apt: pkg=nodejs state=latest update_cache=true