---
- hosts: dbservers
  tasks:
    - name: Install Postgres Database
      tags: postgres
      apt: 
        name={{ item }}
        state=installed
        update_cache=yes
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

    - name: Install MySQL Database
      tags: mysql
      apt:
        name={{ item }}
        state=installed
        update_cache=yes
      with_items:
        - mysql-server 
        - mysql-client
        - libmysqlclient-dev