---
- name: Install Nginx Webserver
  hosts: webservers
  sudo: yes
  roles:
    - nginx

- name: Install Mysql
  hosts: dbservers
  sudo: yes
  roles:
    - mysql

- name: Install PHP FPM
  hosts: appservers
  sudo: yes
  roles:
    - php-fpm