---
- hosts: all
  tasks:
    - name: add user deploy
      sudo: true
      user:
        name=deploy
        append=yes
        groups=sudo
        shell=/bin/bash
        ssh_key_file=~/.ssh/id_rsa

    - name: Set up authorized_keys for the deploy user
      sudo: true
      authorized_key:
        user=deploy
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"